"""Change message text columns to Text

Revision ID: 7d6eab428188
Revises: c37763e32bbe
Create Date: 2026-07-23 15:40:59.766419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6eab428188'
down_revision = 'c37763e32bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('bot_answer',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('bot_answer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1500),
               nullable=True)
        batch_op.alter_column('question',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1500),
               nullable=True)

    # ### end Alembic commands ###
